name: Enable SSH Access to macOS Runner

on: [push, workflow_dispatch]

jobs:
  enable-ssh:
    runs-on: macos-15-large # Update runner type based on your needs

    steps:
    - name: Download ngrok
      run: curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Authenticate ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable SSH
      run: sudo systemsetup -setremotelogin on

    - name: Set Runner Password
      run: |
        sudo dscl . -passwd /Users/runner $PASSWORD
      env:
        PASSWORD: ${{ secrets.USER_PASSWORD }}

    - name: Start ngrok Tunnel
      run: ./ngrok tcp 22 > ngrok.log &
    
    - name: Display ngrok Public URL
      run: sleep 5 && cat ngrok.log | grep -o 'tcp://.*'
